stages:
  - test

image: php:8.2-cli

before_script:
  - apt-get update && apt-get install -y git zip unzip libzip-dev
  - docker-php-ext-install zip
  - cd KickScore
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - chown -R $(id -u):$(id -g) .
  - composer install

phpcs:
  stage: test
  script:
    - vendor/bin/phpcs --standard=PSR12 src/
  allow_failure: false
