<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250106173447 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('SET foreign_key_checks = 0');

        $this->addSql('ALTER TABLE T_CHAMPIONSHIP_CHP CHANGE CHP_ID CHP_ID INT AUTO_INCREMENT NOT NULL, CHANGE CHP_NAME CHP_NAME VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE T_MATCH_MAT DROP FOREIGN KEY FK_T_MATCH_MAT_T_TEAM_TEA');
        $this->addSql('ALTER TABLE T_MATCH_MAT DROP FOREIGN KEY FK_T_MATCH_MAT_T_TEAM_TEA1');
        $this->addSql('DROP INDEX FK_T_MATCH_MAT_T_TEAM_TEA1 ON T_MATCH_MAT');
        $this->addSql('DROP INDEX FK_T_MATCH_MAT_T_TEAM_TEA ON T_MATCH_MAT');
        $this->addSql('ALTER TABLE T_MATCH_MAT CHANGE MAT_ID MAT_ID INT AUTO_INCREMENT NOT NULL, CHANGE TEA_ID TEA_ID INT NOT NULL, CHANGE TEA_ID_MAT_TEAMGREEN TEA_ID_MAT_TEAMGREEN INT NOT NULL, CHANGE MAT_GREENSCORE MAT_GREENSCORE INT DEFAULT NULL, CHANGE MAT_BLUESCORE MAT_BLUESCORE INT DEFAULT NULL, CHANGE MAT_DATE MAT_DATE DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE T_TEAM_TEA DROP FOREIGN KEY FK_T_TEAM_TEA_T_CHAMPIONSHIP_CHP');
        $this->addSql('DROP INDEX FK_T_TEAM_TEA_T_CHAMPIONSHIP_CHP ON T_TEAM_TEA');
        $this->addSql('ALTER TABLE T_TEAM_TEA CHANGE TEA_ID TEA_ID INT AUTO_INCREMENT NOT NULL, CHANGE CHP_ID CHP_ID INT DEFAULT NULL, CHANGE TEA_NAME TEA_NAME VARCHAR(32) NOT NULL, CHANGE TEA_STRUCTURE TEA_STRUCTURE VARCHAR(32) DEFAULT NULL, CHANGE TEA_GAMEPLAYED TEA_GAMEPLAYED INT DEFAULT NULL, CHANGE TEA_WIN TEA_WIN INT DEFAULT NULL, CHANGE TEA_DRAW TEA_DRAW INT DEFAULT NULL, CHANGE TEA_LOSE TEA_LOSE INT DEFAULT NULL, CHANGE TEA_POINTS TEA_POINTS INT DEFAULT NULL');
        $this->addSql('SET foreign_key_checks = 1');
    }


    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('SET foreign_key_checks = 0');
        $this->addSql('ALTER TABLE T_TEAM_TEA CHANGE TEA_ID TEA_ID BIGINT NOT NULL, CHANGE CHP_ID CHP_ID BIGINT DEFAULT NULL, CHANGE TEA_NAME TEA_NAME CHAR(32) NOT NULL, CHANGE TEA_STRUCTURE TEA_STRUCTURE CHAR(32) DEFAULT NULL, CHANGE TEA_GAMEPLAYED TEA_GAMEPLAYED BIGINT DEFAULT NULL, CHANGE TEA_WIN TEA_WIN BIGINT DEFAULT NULL, CHANGE TEA_DRAW TEA_DRAW BIGINT DEFAULT NULL, CHANGE TEA_LOSE TEA_LOSE BIGINT DEFAULT NULL, CHANGE TEA_POINTS TEA_POINTS BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE T_TEAM_TEA ADD CONSTRAINT FK_T_TEAM_TEA_T_CHAMPIONSHIP_CHP FOREIGN KEY (CHP_ID) REFERENCES T_CHAMPIONSHIP_CHP (CHP_ID)');
        $this->addSql('CREATE INDEX FK_T_TEAM_TEA_T_CHAMPIONSHIP_CHP ON T_TEAM_TEA (CHP_ID)');
        $this->addSql('ALTER TABLE T_CHAMPIONSHIP_CHP CHANGE CHP_ID CHP_ID BIGINT NOT NULL, CHANGE CHP_NAME CHP_NAME CHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE T_MATCH_MAT CHANGE MAT_ID MAT_ID BIGINT NOT NULL, CHANGE TEA_ID TEA_ID BIGINT NOT NULL, CHANGE TEA_ID_MAT_TEAMGREEN TEA_ID_MAT_TEAMGREEN BIGINT NOT NULL, CHANGE MAT_GREENSCORE MAT_GREENSCORE BIGINT DEFAULT NULL, CHANGE MAT_BLUESCORE MAT_BLUESCORE BIGINT DEFAULT NULL, CHANGE MAT_DATE MAT_DATE DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE T_MATCH_MAT ADD CONSTRAINT FK_T_MATCH_MAT_T_TEAM_TEA FOREIGN KEY (TEA_ID) REFERENCES T_TEAM_TEA (TEA_ID)');
        $this->addSql('ALTER TABLE T_MATCH_MAT ADD CONSTRAINT FK_T_MATCH_MAT_T_TEAM_TEA1 FOREIGN KEY (TEA_ID_MAT_TEAMGREEN) REFERENCES T_TEAM_TEA (TEA_ID)');
        $this->addSql('CREATE INDEX FK_T_MATCH_MAT_T_TEAM_TEA1 ON T_MATCH_MAT (TEA_ID_MAT_TEAMGREEN)');
        $this->addSql('CREATE INDEX FK_T_MATCH_MAT_T_TEAM_TEA ON T_MATCH_MAT (TEA_ID)');
        $this->addSql('SET foreign_key_checks = 1');
    }
}
