<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250109150047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE T_CHAMPIONSHIP_CHP (CHP_ID INT AUTO_INCREMENT NOT NULL, CHP_NAME VARCHAR(32) DEFAULT NULL, USR_ID INT DEFAULT NULL, INDEX IDX_B634F3D1C4DC529D (USR_ID), PRIMARY KEY(CHP_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE championship_team (championship_id INT NOT NULL, team_id INT NOT NULL, INDEX IDX_E0E6935694DDBCE9 (championship_id), INDEX IDX_E0E69356296CD8AE (team_id), PRIMARY KEY(championship_id, team_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE T_MATCH_MAT (MAT_ID INT AUTO_INCREMENT NOT NULL, MAT_GREENSCORE INT DEFAULT NULL, MAT_BLUESCORE INT DEFAULT NULL, MAT_DATE DATE DEFAULT NULL, TEA_ID INT DEFAULT NULL, TEA_ID_MAT_TEAMGREEN INT DEFAULT NULL, CHP_ID INT DEFAULT NULL, INDEX IDX_7988A88CA28C1B6B (TEA_ID), INDEX IDX_7988A88CD35993D0 (TEA_ID_MAT_TEAMGREEN), INDEX IDX_7988A88CAC6ADD03 (CHP_ID), PRIMARY KEY(MAT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE T_MEMBER_MBR (MBR_ID INT AUTO_INCREMENT NOT NULL, MBR_FNAME VARCHAR(32) NOT NULL, MBR_NAME VARCHAR(32) NOT NULL, MBR_EMAIL VARCHAR(255) NOT NULL, TEA_ID INT NOT NULL, USR_ID INT DEFAULT NULL, INDEX IDX_80E3EC86A28C1B6B (TEA_ID), UNIQUE INDEX UNIQ_80E3EC86C4DC529D (USR_ID), PRIMARY KEY(MBR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE T_TEAM_TEA (TEA_ID INT AUTO_INCREMENT NOT NULL, TEA_NAME VARCHAR(32) NOT NULL, TEA_STRUCTURE VARCHAR(32) DEFAULT NULL, TEA_GAMEPLAYED INT DEFAULT NULL, TEA_WIN INT DEFAULT NULL, TEA_DRAW INT DEFAULT NULL, TEA_LOSE INT DEFAULT NULL, TEA_POINTS INT DEFAULT NULL, PRIMARY KEY(TEA_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_championship (team_id INT NOT NULL, championship_id INT NOT NULL, INDEX IDX_E32BD3A8296CD8AE (team_id), INDEX IDX_E32BD3A894DDBCE9 (championship_id), PRIMARY KEY(team_id, championship_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE T_USER_USR (USR_ID INT AUTO_INCREMENT NOT NULL, USR_FNAME VARCHAR(32) DEFAULT NULL, USR_NAME VARCHAR(32) DEFAULT NULL, USR_EMAIL VARCHAR(32) NOT NULL, USR_ISORG TINYINT(1) NOT NULL, USR_PASSWORD VARCHAR(255) NOT NULL, PRIMARY KEY(USR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE T_CHAMPIONSHIP_CHP ADD CONSTRAINT FK_B634F3D1C4DC529D FOREIGN KEY (USR_ID) REFERENCES T_USER_USR (USR_ID)');
        $this->addSql('ALTER TABLE championship_team ADD CONSTRAINT FK_E0E6935694DDBCE9 FOREIGN KEY (championship_id) REFERENCES T_CHAMPIONSHIP_CHP (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE championship_team ADD CONSTRAINT FK_E0E69356296CD8AE FOREIGN KEY (team_id) REFERENCES T_TEAM_TEA (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE T_MATCH_MAT ADD CONSTRAINT FK_7988A88CA28C1B6B FOREIGN KEY (TEA_ID) REFERENCES T_TEAM_TEA (TEA_ID)');
        $this->addSql('ALTER TABLE T_MATCH_MAT ADD CONSTRAINT FK_7988A88CD35993D0 FOREIGN KEY (TEA_ID_MAT_TEAMGREEN) REFERENCES T_TEAM_TEA (TEA_ID)');
        $this->addSql('ALTER TABLE T_MATCH_MAT ADD CONSTRAINT FK_7988A88CAC6ADD03 FOREIGN KEY (CHP_ID) REFERENCES T_CHAMPIONSHIP_CHP (CHP_ID)');
        $this->addSql('ALTER TABLE T_MEMBER_MBR ADD CONSTRAINT FK_80E3EC86A28C1B6B FOREIGN KEY (TEA_ID) REFERENCES T_TEAM_TEA (TEA_ID)');
        $this->addSql('ALTER TABLE T_MEMBER_MBR ADD CONSTRAINT FK_80E3EC86C4DC529D FOREIGN KEY (USR_ID) REFERENCES T_USER_USR (USR_ID)');
        $this->addSql('ALTER TABLE team_championship ADD CONSTRAINT FK_E32BD3A8296CD8AE FOREIGN KEY (team_id) REFERENCES T_TEAM_TEA (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_championship ADD CONSTRAINT FK_E32BD3A894DDBCE9 FOREIGN KEY (championship_id) REFERENCES T_CHAMPIONSHIP_CHP (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE T_CHAMPIONSHIP_CHP DROP FOREIGN KEY FK_B634F3D1C4DC529D');
        $this->addSql('ALTER TABLE championship_team DROP FOREIGN KEY FK_E0E6935694DDBCE9');
        $this->addSql('ALTER TABLE championship_team DROP FOREIGN KEY FK_E0E69356296CD8AE');
        $this->addSql('ALTER TABLE T_MATCH_MAT DROP FOREIGN KEY FK_7988A88CA28C1B6B');
        $this->addSql('ALTER TABLE T_MATCH_MAT DROP FOREIGN KEY FK_7988A88CD35993D0');
        $this->addSql('ALTER TABLE T_MATCH_MAT DROP FOREIGN KEY FK_7988A88CAC6ADD03');
        $this->addSql('ALTER TABLE T_MEMBER_MBR DROP FOREIGN KEY FK_80E3EC86A28C1B6B');
        $this->addSql('ALTER TABLE T_MEMBER_MBR DROP FOREIGN KEY FK_80E3EC86C4DC529D');
        $this->addSql('ALTER TABLE team_championship DROP FOREIGN KEY FK_E32BD3A8296CD8AE');
        $this->addSql('ALTER TABLE team_championship DROP FOREIGN KEY FK_E32BD3A894DDBCE9');
        $this->addSql('DROP TABLE T_CHAMPIONSHIP_CHP');
        $this->addSql('DROP TABLE championship_team');
        $this->addSql('DROP TABLE T_MATCH_MAT');
        $this->addSql('DROP TABLE T_MEMBER_MBR');
        $this->addSql('DROP TABLE T_TEAM_TEA');
        $this->addSql('DROP TABLE team_championship');
        $this->addSql('DROP TABLE T_USER_USR');
    }
}
