security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\Authenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            switch_user:
                provider: app_user_provider
                role: ROLE_ALLOWED_TO_SWITCH
                parameter: _switch_user
    access_control:
     - { path: ^/admin, roles: ROLE_ADMIN }
     - { path: ^/org, roles: ROLE_ORGANIZER }
     - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_ORGANIZER
        ROLE_ORGANIZER: ROLE_USER, ROLE_ALLOWED_TO_SWITCH
        ROLE_USER: IS_AUTHENTICATED_FULLY
        ROLE_PUBLIC: IS_AUTHENTICATED_ANONYMOUSLY

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10