DELIMITER //

CREATE EVENT IF NOT EXISTS update_match_status
ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN
UPDATE T_MATCH_MAT mat
    INNER JOIN T_TIMESLOT_TSL tsl ON mat.TSL_ID = tsl.TSL_ID
    INNER JOIN T_TEAM_MATCH_STATUS_TMS green_status ON mat.MAT_ID = green_status.MAT_ID AND green_status.TEA_ID = mat.TEA_ID_MAT_TEAMGREEN
    INNER JOIN T_TEAM_MATCH_STATUS_TMS blue_status ON mat.MAT_ID = blue_status.MAT_ID AND blue_status.TEA_ID = mat.TEA_ID_MAT_TEAMBLUE
    SET mat.STS_ID = (SELECT STS_ID FROM T_STATUS_STS WHERE STS_NAME = 'IN_PROGRESS'),
        mat.MAT_GREENSCORE = 0,
        mat.MAT_BLUESCORE = 0
WHERE tsl.TSL_START <= NOW()
  AND NOW() < tsl.TSL_END
  AND mat.STS_ID = (SELECT STS_ID FROM T_STATUS_STS WHERE STS_NAME = 'COMING')
  AND green_status.STS_ID != (SELECT STS_ID FROM T_STATUS_STS WHERE STS_NAME = 'FORFEITED')
  AND blue_status.STS_ID != (SELECT STS_ID FROM T_STATUS_STS WHERE STS_NAME = 'FORFEITED');

UPDATE T_MATCH_MAT mat
    INNER JOIN T_TIMESLOT_TSL tsl ON mat.TSL_ID = tsl.TSL_ID
    SET mat.STS_ID = (SELECT STS_ID FROM T_STATUS_STS WHERE STS_NAME = 'DONE')
WHERE tsl.TSL_END <= NOW()
  AND mat.STS_ID = (SELECT STS_ID FROM T_STATUS_STS WHERE STS_NAME = 'IN_PROGRESS');
END//

DELIMITER ;